version: '3.8'

services:
    php:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:80
        volumes:
            - ./public:/var/www/html/
            - ./:/var/www/
        container_name: 'php-apache'
        working_dir: /var/www/html/
        restart: always

    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: 123456
        container_name: 'db-mysql'
        ports:
            - 3306:3306
        volumes:
            - ./volumes/mysql/data:/var/lib/mysql

    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
        container_name: 'db-adminer'
